# Vectorize the 6 line-art poses: lines via potrace, blush discs as fitted circles.
# usage: python3 scripts/trace-line-art.py <moodboard.png>   (needs potrace)
import json, re, subprocess, sys
import numpy as np
from PIL import Image, ImageFilter

SRC = sys.argv[1]  # moodboard PNG exported from Figma ("image 5")
UP = 4
CELLS = {  # (x0, y0, x1, y1) in source px
    'raise-palpate': (0, 0, 335, 388), 'cross-squeeze': (335, 0, 700, 388), 'nipple': (700, 0, 1109, 388),
    'shoulder': (0, 388, 341, 739), 'side': (341, 388, 667, 739), 'lift': (667, 388, 1109, 739),
}

im = Image.open(SRC).convert('RGBA')
bg = Image.new('RGBA', im.size, (255, 255, 255, 255)); bg.alpha_composite(im)
rgb = bg.convert('RGB')
out = {}
for name, (x0, y0, x1, y1) in CELLS.items():
    crop = rgb.crop((x0, y0, x1, y1))
    w, h = crop.size
    big = crop.resize((w * UP, h * UP), Image.LANCZOS).filter(ImageFilter.GaussianBlur(UP * 0.4))
    a = np.asarray(big).astype(float)
    lum = 0.299 * a[..., 0] + 0.587 * a[..., 1] + 0.114 * a[..., 2]
    # thin strokes are light grey after anti-aliasing + JPEG: loose threshold, then close the gaps
    ink = Image.fromarray(np.where(lum < 196, 255, 0).astype(np.uint8))
    ink = ink.filter(ImageFilter.MaxFilter(7)).filter(ImageFilter.MinFilter(7))
    tmp = f'/tmp/lineart-{name}'
    Image.fromarray(255 - np.asarray(ink)).convert('1').save(f'{tmp}.bmp')
    subprocess.run(['potrace', f'{tmp}.bmp', '-s', '-o', f'{tmp}.svg', '-t', '12', '-a', '1.15', '-O', '0.8', '-u', '10'], check=True)
    svg = open(f'{tmp}.svg').read()
    tr = re.search(r'<g transform="([^"]+)"', svg).group(1)
    paths = re.findall(r'<path d="([^"]+)"', svg, re.S)
    d = ' '.join(p.replace('\n', ' ') for p in paths)
    # blush disc: pink pixels in the (non-upscaled) cell, fitted as a circle
    c = np.asarray(crop).astype(int)
    l2 = 0.299 * c[..., 0] + 0.587 * c[..., 1] + 0.114 * c[..., 2]
    pink = (c[..., 0] - c[..., 1] > 12) & (l2 > 170)
    ys, xs = np.nonzero(pink)
    cx, cy = xs.mean(), ys.mean()
    r = float(np.sqrt(pink.sum() / np.pi))
    # potrace works in upscaled px; express everything in source px of the cell
    out[name] = {'w': w, 'h': h, 'transform': f'scale({1/UP}) {tr}', 'd': d, 'disc': [round(cx, 1), round(cy, 1), round(r * 1.04, 1)]}
    print(name, w, h, 'paths', len(paths), 'chars', len(d), 'disc', out[name]['disc'])

ts = '// Generated by scripts/trace-line-art.py from the moodboard line art (Figma "image 5"). Do not edit by hand.\n'
ts += 'export const LINE_ART = ' + json.dumps(out, indent=1) + ' as const;\n'
ts += 'export type LineArtName = keyof typeof LINE_ART;\n'
open('src/components/lineArtData.ts', 'w').write(ts)
